FROM node:22-alpine AS frontend-dev
WORKDIR /workspace/frontend
COPY frontend/package*.json ./
RUN npm ci
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]

FROM node:22-alpine AS admin-dev
WORKDIR /workspace/admin
COPY admin/package*.json ./
RUN npm ci
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3001"]

FROM golang:1.25-alpine AS backend-dev
RUN apk add --no-cache gcc musl-dev \
	&& go install github.com/air-verse/air@v1.64.0
ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
CMD ["air", "-c", ".air.toml"]
