export interface CustomCSSPreset {
  id: string;
  label: string;
  description: string;
  swatch: string;
  colors: Record<string, string>;
}

export const CUSTOM_CSS_PRESETS: CustomCSSPreset[] = [
  {
    id: "red",
    label: "红",
    description: "玫瑰砖红",
    swatch: "#b84f5a",
    colors: {
      "--page-background-color": "#fff6f5",
      "--color-page-foreground": "#472f34",
      "--color-surface": "#fffafa",
      "--color-surface-foreground": "#472f34",
      "--color-overlay": "#fffafa",
      "--color-overlay-foreground": "#472f34",
      "--color-brand": "#b84f5a",
      "--color-brand-foreground": "#fffafa",
      "--color-nav-foreground": "#fffafa",
      "--color-control-secondary": "#f6e1df",
      "--color-control-secondary-foreground": "#684047",
      "--color-surface-muted": "#f6e1df",
      "--color-text-muted": "#956e73",
      "--color-control-hover": "#f1cbc9",
      "--color-control-hover-foreground": "#684047",
      "--color-danger": "#a93d48",
      "--color-control-border": "#e2c5c2",
      "--color-input-border": "#e2c5c2",
      "--color-focus-ring": "#d18b8d",
      "--color-fabric-stitch": "#d39a98",
      "--color-fabric-shadow": "rgba(139, 54, 63, 0.12)",
      "--color-fabric-grain": "#f0d9d6",
    },
  },
  {
    id: "orange",
    label: "橙",
    description: "暖橙陶土",
    swatch: "#c86d32",
    colors: {
      "--page-background-color": "#fff8f0",
      "--color-page-foreground": "#49352a",
      "--color-surface": "#fffdf9",
      "--color-surface-foreground": "#49352a",
      "--color-overlay": "#fffdf9",
      "--color-overlay-foreground": "#49352a",
      "--color-brand": "#c86d32",
      "--color-brand-foreground": "#fffdf9",
      "--color-nav-foreground": "#fffdf9",
      "--color-control-secondary": "#f6e6d5",
      "--color-control-secondary-foreground": "#70482f",
      "--color-surface-muted": "#f6e6d5",
      "--color-text-muted": "#9a7861",
      "--color-control-hover": "#f2d2b5",
      "--color-control-hover-foreground": "#70482f",
      "--color-danger": "#b74b3c",
      "--color-control-border": "#e4c9ad",
      "--color-input-border": "#e4c9ad",
      "--color-focus-ring": "#d99a65",
      "--color-fabric-stitch": "#d5a273",
      "--color-fabric-shadow": "rgba(145, 74, 30, 0.12)",
      "--color-fabric-grain": "#efddc6",
    },
  },
  {
    id: "yellow",
    label: "黄",
    description: "蜂蜜麦秆",
    swatch: "#a77b19",
    colors: {
      "--page-background-color": "#fffbed",
      "--color-page-foreground": "#443a20",
      "--color-surface": "#fffef8",
      "--color-surface-foreground": "#443a20",
      "--color-overlay": "#fffef8",
      "--color-overlay-foreground": "#443a20",
      "--color-brand": "#a77b19",
      "--color-brand-foreground": "#fffef8",
      "--color-nav-foreground": "#fffef8",
      "--color-control-secondary": "#f5edc9",
      "--color-control-secondary-foreground": "#65521c",
      "--color-surface-muted": "#f5edc9",
      "--color-text-muted": "#958353",
      "--color-control-hover": "#eee0a9",
      "--color-control-hover-foreground": "#65521c",
      "--color-danger": "#b94d3c",
      "--color-control-border": "#ded19e",
      "--color-input-border": "#ded19e",
      "--color-focus-ring": "#c8a846",
      "--color-fabric-stitch": "#cbb66d",
      "--color-fabric-shadow": "rgba(125, 92, 15, 0.12)",
      "--color-fabric-grain": "#eee5bd",
    },
  },
  {
    id: "green",
    label: "绿",
    description: "鼠尾草森林",
    swatch: "#438061",
    colors: {
      "--page-background-color": "#f2faf5",
      "--color-page-foreground": "#2f4035",
      "--color-surface": "#fbfffc",
      "--color-surface-foreground": "#2f4035",
      "--color-overlay": "#fbfffc",
      "--color-overlay-foreground": "#2f4035",
      "--color-brand": "#438061",
      "--color-brand-foreground": "#fbfffc",
      "--color-nav-foreground": "#fbfffc",
      "--color-control-secondary": "#dceee2",
      "--color-control-secondary-foreground": "#385c48",
      "--color-surface-muted": "#dceee2",
      "--color-text-muted": "#6f9680",
      "--color-control-hover": "#c6e2d0",
      "--color-control-hover-foreground": "#385c48",
      "--color-danger": "#b64c4a",
      "--color-control-border": "#bfd9c8",
      "--color-input-border": "#bfd9c8",
      "--color-focus-ring": "#79ad8e",
      "--color-fabric-stitch": "#8ab69a",
      "--color-fabric-shadow": "rgba(42, 101, 67, 0.12)",
      "--color-fabric-grain": "#d9ebdf",
    },
  },
  {
    id: "cyan",
    label: "青",
    description: "海盐青绿",
    swatch: "#187e83",
    colors: {
      "--page-background-color": "#effafa",
      "--color-page-foreground": "#294247",
      "--color-surface": "#fbffff",
      "--color-surface-foreground": "#294247",
      "--color-overlay": "#fbffff",
      "--color-overlay-foreground": "#294247",
      "--color-brand": "#187e83",
      "--color-brand-foreground": "#fbffff",
      "--color-nav-foreground": "#fbffff",
      "--color-control-secondary": "#d9eff0",
      "--color-control-secondary-foreground": "#2f6064",
      "--color-surface-muted": "#d9eff0",
      "--color-text-muted": "#6b9498",
      "--color-control-hover": "#c0e3e5",
      "--color-control-hover-foreground": "#2f6064",
      "--color-danger": "#b64f55",
      "--color-control-border": "#bddbdd",
      "--color-input-border": "#bddbdd",
      "--color-focus-ring": "#73afb1",
      "--color-fabric-stitch": "#83babc",
      "--color-fabric-shadow": "rgba(16, 103, 108, 0.12)",
      "--color-fabric-grain": "#d5ebeb",
    },
  },
  {
    id: "blue",
    label: "蓝",
    description: "雾蓝靛青",
    swatch: "#466ba5",
    colors: {
      "--page-background-color": "#f3f7ff",
      "--color-page-foreground": "#303b52",
      "--color-surface": "#fcfdff",
      "--color-surface-foreground": "#303b52",
      "--color-overlay": "#fcfdff",
      "--color-overlay-foreground": "#303b52",
      "--color-brand": "#466ba5",
      "--color-brand-foreground": "#fcfdff",
      "--color-nav-foreground": "#fcfdff",
      "--color-control-secondary": "#e0e9f8",
      "--color-control-secondary-foreground": "#3d5680",
      "--color-surface-muted": "#e0e9f8",
      "--color-text-muted": "#7589aa",
      "--color-control-hover": "#cbdaf1",
      "--color-control-hover-foreground": "#3d5680",
      "--color-danger": "#b24d57",
      "--color-control-border": "#c7d5ea",
      "--color-input-border": "#c7d5ea",
      "--color-focus-ring": "#829dcc",
      "--color-fabric-stitch": "#91a9ce",
      "--color-fabric-shadow": "rgba(49, 82, 135, 0.12)",
      "--color-fabric-grain": "#dce6f5",
    },
  },
  {
    id: "purple",
    label: "紫",
    description: "薰衣草紫灰",
    swatch: "#7657a5",
    colors: {
      "--page-background-color": "#f8f4ff",
      "--color-page-foreground": "#3e354b",
      "--color-surface": "#fefcff",
      "--color-surface-foreground": "#3e354b",
      "--color-overlay": "#fefcff",
      "--color-overlay-foreground": "#3e354b",
      "--color-brand": "#7657a5",
      "--color-brand-foreground": "#fefcff",
      "--color-nav-foreground": "#fefcff",
      "--color-control-secondary": "#ebe2f7",
      "--color-control-secondary-foreground": "#5a4779",
      "--color-surface-muted": "#ebe2f7",
      "--color-text-muted": "#8979a2",
      "--color-control-hover": "#dcd0ef",
      "--color-control-hover-foreground": "#5a4779",
      "--color-danger": "#b04f5e",
      "--color-control-border": "#d6c9e8",
      "--color-input-border": "#d6c9e8",
      "--color-focus-ring": "#a38cc8",
      "--color-fabric-stitch": "#ab98cc",
      "--color-fabric-shadow": "rgba(91, 58, 141, 0.12)",
      "--color-fabric-grain": "#e5daf2",
    },
  },
  {
    id: "black",
    label: "黑",
    description: "炭黑银灰",
    swatch: "#30343b",
    colors: {
      "--page-background-color": "#f1f3f5",
      "--color-page-foreground": "#252931",
      "--color-surface": "#ffffff",
      "--color-surface-foreground": "#252931",
      "--color-overlay": "#ffffff",
      "--color-overlay-foreground": "#252931",
      "--color-brand": "#30343b",
      "--color-brand-foreground": "#ffffff",
      "--color-nav-foreground": "#ffffff",
      "--color-control-secondary": "#e2e5e9",
      "--color-control-secondary-foreground": "#444b55",
      "--color-surface-muted": "#e2e5e9",
      "--color-text-muted": "#737b87",
      "--color-control-hover": "#d4d8de",
      "--color-control-hover-foreground": "#30343b",
      "--color-danger": "#ad4e52",
      "--color-control-border": "#cdd2d9",
      "--color-input-border": "#cdd2d9",
      "--color-focus-ring": "#8e98a6",
      "--color-fabric-stitch": "#9ca5b1",
      "--color-fabric-shadow": "rgba(40, 45, 53, 0.14)",
      "--color-fabric-grain": "#dde1e6",
    },
  },
  {
    id: "white",
    label: "白",
    description: "云朵白蓝",
    swatch: "#718096",
    colors: {
      "--page-background-color": "#ffffff",
      "--color-page-foreground": "#344054",
      "--color-surface": "#ffffff",
      "--color-surface-foreground": "#344054",
      "--color-overlay": "#ffffff",
      "--color-overlay-foreground": "#344054",
      "--color-brand": "#718096",
      "--color-brand-foreground": "#ffffff",
      "--color-nav-foreground": "#ffffff",
      "--color-control-secondary": "#f2f4f7",
      "--color-control-secondary-foreground": "#475467",
      "--color-surface-muted": "#f2f4f7",
      "--color-text-muted": "#98a2b3",
      "--color-control-hover": "#e7ebf0",
      "--color-control-hover-foreground": "#344054",
      "--color-danger": "#b54747",
      "--color-control-border": "#d0d5dd",
      "--color-input-border": "#d0d5dd",
      "--color-focus-ring": "#98a2b3",
      "--color-fabric-stitch": "#b8c0cc",
      "--color-fabric-shadow": "rgba(52, 64, 84, 0.1)",
      "--color-fabric-grain": "#edf0f3",
    },
  },
];

export function applyColorPreset(css: string, preset: CustomCSSPreset): string {
  return Object.entries(preset.colors).reduce((result, [name, value]) => {
    const pattern = new RegExp(`(^\\s*)${name.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}\\s*:[^;]+;`, "m");
    return pattern.test(result)
      ? result.replace(pattern, `$1${name}: ${value};`)
      : `${result.trimEnd()}\n\n:root {\n  ${name}: ${value};\n}\n`;
  }, css);
}
